name = "chen xiang"
avatar = "images/avatar.png" # Avatar image. Default to "images/profile.webp".
bio = "frontend、nodejs Engineer."
company = "保密"
location = "深圳市软件大厦"
# alternatives:
# location = "<a href='https://www.openstreetmap.org/search?query=Earth'>Earth</a>"
# location = "<a href='https://www.google.com/maps/search/Earth'>Earth</a>"
# about = "https://domain.tld" # The external about page. The internal about page will be used if not set.

[params]
  #layout = "compact"
