[[main]]
  name = "支持"
  identifier = "support"
  pre = '<i class="fas fa-fw fa-chevron-circle-down"></i>'
  weight = 100
[[main]]
  name = "Bug Report"
  identifier = "bug-report"
  parent = "support"
  url = "https://github.com/cx5397/iqianduan/issues"
  weight = 4
[[main]]
  parent = "support"
  weight = 8
  [main.params]
    divider = true
[[main]]
  identifier = "demo-netlify"
  parent = "support"
  name = "Demo(Netlify)"
  weight = 9
  url = "https://hbs.razonyang.com"
[[main]]
  identifier = "demo-china"
  parent = "support"
  name = "Demo(China)"
  weight = 10
  url = "https://hbs-cn.razonyang.com"
